FROM python:3.8
#FROM python:3.12-rc-alpine
WORKDIR /app
COPY . .
RUN pip install --upgrade pip && pip install -r requirements.txt
#RUN python tests/test.py
EXPOSE 8000
ENV ENVIRONMENT=DEV
ENV HOST=localhost
ENV PORT=8000
ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379
ENV REDIS_DB=0
CMD ["python", "hello.py"]
