FROM python:3.8.15-alpine3.16
#FROM python:3.12-rc-alpine
WORKDIR /app
COPY . .
RUN pip install --upgrade pip && pip install -r requirements.txt
RUN python tests/test.py
#EXPOSE 8000
RUN export $(cat .env | xargs) 
#&& python hello.py
#CMD ["node", "src/index.js"]
CMD ["python", "hello.py"]

